### ISSUE TITLE
1000 file limit

### ISSUE THREAD

**Issue by RBraxton** [nolanlawson/pretty-s3-index-html#1]
Need to extend tool to allow for more than 1000 files.

To get more than 1000 objects, you must make multiple requests using the Marker parameter to tell S3 where you left off for each request.

**Comment by spuder** [comment]
The link is broken. Is this the shrub you are referring to? 

https://github.com/gabriel/shrub

**Comment by nolanlawson** [comment]
Yeah. Looks like the service is down.

**Comment by oscherler** [comment]
I implemented handling of IsTruncated in my fork: [oscherler/pretty-s3-index-html](https://github.com/oscherler/pretty-s3-index-html).

**Comment by nolanlawson** [comment]
This project is archived, so I am closing this issue. Thanks!
