### ISSUE TITLE
Incorporate the improvements from forks into mainline

### ISSUE THREAD

**Issue by cristim** [nolanlawson/pretty-s3-index-html#6]
I've seen there is quite some progress done by @nagornyi, @oscherler and @Jimmy-Xu in their respective forks.

It would be nice to have all this work merged back into the @nolanlawson's original repository.

**Comment by jdyach** [comment]
Does anyone have a fully-functional version of this script?

**Comment by cristim** [comment]
I  have it in use at 
https://cloudprowess.s3.amazonaws.com/index.html, but I don't remember which of the forks was it from.

It's working well, I didn't notice any issues so far.

**Comment by abal5** [comment]
@jdyach try this fork it works for me

https://github.com/Hayorti/pretty-s3-index-html/blob/master/index.html

**Comment by nolanlawson** [comment]
This project is archived, so I am closing this issue. Thanks!

**Comment by mbesjisp** [comment]
Hello Nolan Lawson,



i interest with your github pretty-s3-index-html



https://nolanlawson.s3.amazonaws.com/index.html



can you help me how open subfolders so folders can list on index ?



my public policy permission standart just like this :

{

    "Version": "2012-10-17",

    "Statement": [

        {

            "Sid": "AllowPublicRead",

            "Effect": "Allow",

            "Principal": "*",

            "Action": "s3:*",

            "Resource": "arn:aws:s3:::my-bucket/*"

        }

    ]

}

**Comment by 15b883** [comment]
@cristim Can you share your index.html file？

**Comment by cristim** [comment]
@15b883 have a look at https://cloudprowess.s3.amazonaws.com/index.html

**Comment by 15b883** [comment]
@cristim thx~

**Comment by qoomon** [comment]
I did a rewrite in vue, without the need of using fake folders. **[Demo](https://qoomon.github.io/aws-s3-bucket-browser/?bucket=https://s3.eu-west-1.amazonaws.com/data.openspending.org)**

https://github.com/qoomon/aws-s3-bucket-browser

**Comment by vsem-cinch** [comment]
Hi @qoomon. I did all the steps but I still get an empty listing. Is there anything you can think off that I may be missing? Thanks!
http://util.cinchhs.com.s3-website-us-east-1.amazonaws.com

**Comment by vsem-cinch** [comment]
Oh never mind I figure it out. Thanks!
