### ISSUE TITLE
Print View

### ISSUE THREAD

**Issue by kchaitu4** [nolanlawson/pretty-s3-index-html#7]
Probably you can also add a option for print friendly view as the current one do not display print friendly.

Thanks,
Krishna
kchaitu4 at the rate gmail dot com

**Comment by nolanlawson** [comment]
This project is archived, so I am closing this issue. Thanks!

**Comment by philo123** [comment]
Thanks. Do you know any live project for the same purpose? I tried using this project, but it did not work as it got hanged.
